### PR TITLE
Revert "Disable SMP."

### PR DESCRIPTION
**Pull request by jkstrick-k4**
This reverts commit 9284726b72ad09300ac5cd3412170180bfc810ca.

### CODE REVIEW

**Comment by fantareinos** [comment]
What's the motivation for re-enabling SMP writing?

**Comment by CTunstall** [comment]
@anurag-k4 SMP writing was disabled due to interference with bluez, but now that we have disabled bluez, this interference will no longer occur.  I do still have a question on this for @jkstrick-k4 as far as I  assume it is better to re-enable this, now that bluez is gone, just so that having it disabled doesn't cause issues with something else?

**Comment by fantareinos** [comment]
Have we discovered that re-enabling SMP writing causes issues elsewhere?

**Comment by CTunstall** [comment]
@anurag-k4 I don't believe we have seen any functional issues with SMP writing re-enabled.  @jkstrick-k4 to confirm.

**Comment by jkstrick-k4** [comment]
SMP is the protocol used for authentication.  We need it in order to do passkey authentication.  We disabled it before because BlueZ was handling SMP / Passkey auth and noble was interfering in the handshaking and causing it to fail.  Now that BlueZ is not being used, we need noble to handle SMP.

**Review by CTunstall — APPROVED** [review]

**Review by fantareinos — APPROVED** [review]

**Pull request merged**
